name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore ./src/CCFCleanMinimalApiLib/CCFCleanMinimalApiLib.csproj
    - name: Build the project
      run: dotnet build ./src/CCFCleanMinimalApiLib/CCFCleanMinimalApiLib.csproj -c Release
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3 
    - name: Clean up existing .nupkg files
      run: rm -f *.nupkg
    - name: Pack NuGet Package
      run: nuget pack ./src/Package.nuspec -OutputDirectory . -Properties Configuration=Release -NoDefaultExcludes
    - name: Push to NuGet
      run: nuget push *.nupkg -ApiKey ${{secrets.nuget_api_key}} -Source https://api.nuget.org/v3/index.json